{"name": "test_login_password_error_case", "status": "broken", "statusDetails": {"message": "NameError: name 'login' is not defined", "trace": "self = <PrimarySelenium.case.login.test_login_case.TestLoginCase object at 0x03DD7520>, init_login = <bussiness.login_bussiness.LoginBussiness object at 0x03E3DF10>\n\n    @pytest.mark.usefixtures(\"init_driver\")\n    def test_login_password_error_case(self, init_login):\n    \n        init_login.login(\"13544989573\", \"111111\")\n>       assert init_login.check_login_fail() == False\n\ncase\\login\\test_login_case.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <bussiness.login_bussiness.LoginBussiness object at 0x03E3DF10>, phone = '13544989573', password = '111111'\n\n    def login(self, phone, password):\n>       login.login(phone, password)\nE       NameError: name 'login' is not defined\n\nbussiness\\login_bussiness.py:12: NameError"}, "attachments": [{"name": "log", "source": "7619375c-181c-4131-8c09-c8a524984afd-attachment.txt", "type": "text/plain"}], "start": 1597502672386, "stop": 1597502672387, "uuid": "7c656492-26a3-4b84-81c5-37d755c9a6c4", "historyId": "8c75e61dfeaf40e00fbf3596d8f857c6", "testCaseId": "e31b71ea53c9108f5a105705e791d0a6", "fullName": "case.login.test_login_case.TestLoginCase#test_login_password_error_case", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "case.login"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "FYYX-2019VXOSDQ"}, {"name": "thread", "value": "20516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.login.test_login_case"}]}