INFO     util.usr_log:basepage.py:28 {'开始打开chrome浏览器'}
INFO     util.usr_log:basepage.py:54 开始打开地址 http://eshop.tslj.cn/#/login
INFO     util.usr_log:basepage.py:113 对窗口的操作-最大化
INFO     util.usr_log:basepage.py:350 查找 登录页面_查找手机号输入框 中的第 1 个元素 login_phone_parent
INFO     util.usr_log:basepage.py:87 等待元素 login_phone_parent 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:49.940979，结束等待时间点：2020-11-20 19:48:49.989982，等待时长为：0:00:00.049003
INFO     util.usr_log:basepage.py:264 查找 登录页面_查找手机号输入框 中的元素 login_phone_parent
INFO     util.usr_log:basepage.py:307 查找 登录页面_查找手机号输入框 中的元素 login_phone_children
INFO     util.usr_log:basepage.py:371 在 登录页面_输入手机号 值为 13544989573
INFO     util.usr_log:basepage.py:350 查找 登录页面_查找密码输入框 中的第 2 个元素 login_password_parent
INFO     util.usr_log:basepage.py:87 等待元素 login_password_parent 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:50.388005，结束等待时间点：2020-11-20 19:48:50.430007，等待时长为：0:00:00.042002
INFO     util.usr_log:basepage.py:264 查找 登录页面_查找密码输入框 中的元素 login_password_parent
INFO     util.usr_log:basepage.py:307 查找 登录页面_查找密码输入框 中的元素 login_password_children
INFO     util.usr_log:basepage.py:371 在 登录页面_输入密码 值为 111111
INFO     util.usr_log:basepage.py:87 等待元素 login_button 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:50.706023，结束等待时间点：2020-11-20 19:48:50.766026，等待时长为：0:00:00.060003
INFO     util.usr_log:basepage.py:191 查找 登录页面_点击登录按钮 中的元素 login_button
INFO     util.usr_log:basepage.py:386 点击 登录页面_点击登录按钮  中的元素 login_button
INFO     util.usr_log:basepage.py:87 等待元素 search_input 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:52.911149，结束等待时间点：2020-11-20 19:48:52.973153，等待时长为：0:00:00.062004
INFO     util.usr_log:basepage.py:191 查找 搜索框_输入搜索内容 中的元素 search_input
INFO     util.usr_log:basepage.py:87 等待元素 search_input 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:53.403177，结束等待时间点：2020-11-20 19:48:53.434179，等待时长为：0:00:00.031002
INFO     util.usr_log:basepage.py:191 查找 搜索框_敲回车 中的元素 search_input
INFO     util.usr_log:basepage.py:479 在 search_input 元素 搜索框_敲回车 
INFO     util.usr_log:basepage.py:87 等待元素 first_pic 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:53.910206，结束等待时间点：2020-11-20 19:48:54.033213，等待时长为：0:00:00.123007
INFO     util.usr_log:basepage.py:191 查找 商品列表页_跳转到详情页 中的元素 first_pic
INFO     util.usr_log:basepage.py:386 点击 商品列表页_跳转到详情页  中的元素 first_pic
INFO     util.usr_log:basepage.py:87 等待元素 add_cart_button 可见。
INFO     util.usr_log:basepage.py:97 开始等待时间点：2020-11-20 19:48:54.564244，结束等待时间点：2020-11-20 19:48:55.399291，等待时长为：0:00:00.835047
INFO     util.usr_log:basepage.py:191 查找 商品详情页_添加到购物车 中的元素 add_cart_button
INFO     util.usr_log:basepage.py:386 点击 商品详情页_添加到购物车  中的元素 add_cart_button
INFO     util.usr_log:basepage.py:87 等待元素 decrease_button 可见。
ERROR    util.usr_log:basepage.py:101 等待元素可见失败：
Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 94, in wait_eleVisible
    WebDriverWait(self.driver, timeout, frequency).until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=84.0.4147.105)

ERROR    util.usr_log:basepage.py:153 网页截图失败！
Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 94, in wait_eleVisible
    WebDriverWait(self.driver, timeout, frequency).until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=84.0.4147.105)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 150, in save_screen
    self.driver.save_screenshot(screen_path)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=84.0.4147.105)