INFO     util.usr_log:basepage.py:28 {'开始打开chrome浏览器'}
INFO     util.usr_log:basepage.py:54 开始打开地址 http://eshop.tslj.cn/#/login
INFO     util.usr_log:basepage.py:113 对窗口的操作-最大化
INFO     util.usr_log:basepage.py:350 查找 登录页面_查找手机号输入框 中的第 1 个元素 login_phone_parent
INFO     util.usr_log:basepage.py:87 等待元素 login_phone_parent 可见。
ERROR    util.usr_log:basepage.py:101 等待元素可见失败：
Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 94, in wait_eleVisible
    WebDriverWait(self.driver, timeout, frequency).until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'
ERROR    util.usr_log:basepage.py:153 网页截图失败！
Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 94, in wait_eleVisible
    WebDriverWait(self.driver, timeout, frequency).until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'NoneType' object has no attribute 'is_displayed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyProject\PrimarySelenium\base\basepage.py", line 150, in save_screen
    self.driver.save_screenshot(screen_path)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=84.0.4147.105)