{"uuid": "d570b123-c62e-44c0-badf-29d06f0548cc", "children": ["a58edb68-7d94-49ed-8551-7256c7d4b35d"], "befores": [{"name": "init_cart", "status": "passed", "start": 1605863645019, "stop": 1605863645019}], "afters": [{"name": "init_cart::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=84.0.4147.105)\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\pyProject\\PrimarySelenium\\case\\shoppingcart\\conftest.py\", line 25, in init_cart\n    init_driver.get_cookies()\n  File \"D:\\pyProject\\PrimarySelenium\\base\\basepage.py\", line 414, in get_cookies\n    cookie = self.driver.get_cookies()\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 841, in get_cookies\n    return self.execute(Command.GET_ALL_COOKIES)['value']\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1605863693236, "stop": 1605863697331}], "start": 1605863645019, "stop": 1605863697331}